In [ ]:
import numpy as np# convert the list to array
lst =list(range(1,25))
arr=np.array(lst)
print(type(lst))




<class 'list'>


In [8]:
arr=np.arange(1,25)# arange()=used to create the array
arr# single dimensional arry

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [13]:
arr=np.ones((5,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#2d array
arr=np.zeros((5,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
#2d array
arr=np.array(([1,2,3],[4,5,6])),  (([12,4,5],[2,34,4]))
arr

(array([[1, 2, 3],
        [4, 5, 6]]),
 ([12, 4, 5], [2, 34, 4]))

In [86]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.dot(a,b))

[[19 22]
 [43 50]]


In [ ]:
#creating numpy array
import numpy as np

lst=list(range(5))
print(lst)
print(arr)

[0, 1, 2, 3, 4]
[1 2 3 4]


In [20]:
#creating a 3d array (2 block ,3 row,4columan )
arr=np.array([[[1,2,3,2],[4,5,6,4],[6,7,8,5]],[[2,3,4,6],[2,4,67,7],[5,7,8,9]]])
arr

array([[[ 1,  2,  3,  2],
        [ 4,  5,  6,  4],
        [ 6,  7,  8,  5]],

       [[ 2,  3,  4,  6],
        [ 2,  4, 67,  7],
        [ 5,  7,  8,  9]]])

In [22]:
#create onens 
arr=np.ones((1,2))
arr

array([[1., 1.]])

In [ ]:
arr

In [ ]:
arr=np.linspace(1,10,5).reshape(5,1)#reshape=used to row(5) and columan(1)
arr # linspace=equal space start =1, end =10 ,random value=5 value create array in the interval

array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [46]:

arr=np.arange(0,30).reshape(5,6)

# reshaping 1d to 2d convert 
arr


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
list_2d=[[1,2,3],[1,4,5],[3,4,5]]#2d list convert into array
list_2d


[[1, 2, 3], [1, 4, 5], [3, 4, 5]]

In [24]:
arr=np.array(list_2d)
arr.ndim
arr.shape
arr

array([[1, 2, 3],
       [1, 4, 5],
       [3, 4, 5]])

In [27]:
arr.T

array([[1, 1, 3],
       [2, 4, 4],
       [3, 5, 5]])

In [ ]:

#convert the 2d to 3d 
arr.reshape(3,5,2)# 3  block 5 row ,2 columan

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]]])

In [ ]:
# random initization number replit hoge 
arr=np.random.randint(1,5,27) # 1d array # value randint  integer hoga 
arr

array([1, 1, 4, 4, 2, 1, 1, 4, 1, 2, 1, 2, 2, 2, 2, 4, 2, 3, 3, 2, 2, 2,
       3, 1, 3, 4, 4])

In [ ]:
arr=np.random.randint(1,5,(3,3))# 2d array
arr

array([[1, 4, 2],
       [4, 4, 4],
       [1, 2, 2]])

In [ ]:
arr=np.random.random((3,3))# 2d arr
arr

array([[0.51496708, 0.42049682, 0.54918581],
       [0.12667884, 0.258567  , 0.79762101],
       [0.83194729, 0.22586765, 0.21434265]])

In [ ]:
arr=np.arange(60)
arr # slicing to start(0 )
                      # position to start 1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [31]:
                           # slicing to start(0 )
arr[2]                        # position to start 1

2

In [32]:
arr[3:11]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#1d arrarr[10:60]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
arr[0:20:2]#0 start point,20 end point ,2 space point

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
 arr=np.arange(60)
 arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [40]:
 arr=arr.reshape(12,5)
 arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [41]:
arr[1]

array([5, 6, 7, 8, 9])

In [43]:
arr[0:5]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr[0:5,1:2]#1 colum element acess

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [46]:
arr[2,3]

13

In [47]:
arr[11,4]

59

In [48]:
arr[11][-1]

59

In [ ]:
arr[-1][-1]#-1 last row ,-1 column

In [42]:
arr[1,1]

6

In [49]:
arr[:4][-1]

array([15, 16, 17, 18, 19])

In [ ]:
arr[4,2]  =100# 2d array
arr# replace one element to other elemt   

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21, 100,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [ ]:
arr[5,3]=29#5 rows and 3 column
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21, 100,  23,  24],
       [ 25,  26,  27,  29,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [ ]:
arr=np.arange(225)# 3d array
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [59]:
arr=arr.reshape(5,15,3)
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [60]:
arr.shape

(5, 15, 3)

In [61]:
arr[1]

array([[45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89]])

In [62]:
arr[0][2:7]

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [63]:
arr[:,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [64]:
arr[2][3][1]=500

In [66]:
arr[2][3][1]
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 500, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [67]:
arr[2]

array([[ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 500, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124, 125],
       [126, 127, 128],
       [129, 130, 131],
       [132, 133, 134]])

In [68]:
arr+2

array([[[  2,   3,   4],
        [  5,   6,   7],
        [  8,   9,  10],
        [ 11,  12,  13],
        [ 14,  15,  16],
        [ 17,  18,  19],
        [ 20,  21,  22],
        [ 23,  24,  25],
        [ 26,  27,  28],
        [ 29,  30,  31],
        [ 32,  33,  34],
        [ 35,  36,  37],
        [ 38,  39,  40],
        [ 41,  42,  43],
        [ 44,  45,  46]],

       [[ 47,  48,  49],
        [ 50,  51,  52],
        [ 53,  54,  55],
        [ 56,  57,  58],
        [ 59,  60,  61],
        [ 62,  63,  64],
        [ 65,  66,  67],
        [ 68,  69,  70],
        [ 71,  72,  73],
        [ 74,  75,  76],
        [ 77,  78,  79],
        [ 80,  81,  82],
        [ 83,  84,  85],
        [ 86,  87,  88],
        [ 89,  90,  91]],

       [[ 92,  93,  94],
        [ 95,  96,  97],
        [ 98,  99, 100],
        [101, 502, 103],
        [104, 105, 106],
        [107, 108, 109],
        [110, 111, 112],
        [113, 114, 115],
        [116, 117, 118],
        [119, 120, 12

In [69]:
arr -1

array([[[ -1,   0,   1],
        [  2,   3,   4],
        [  5,   6,   7],
        [  8,   9,  10],
        [ 11,  12,  13],
        [ 14,  15,  16],
        [ 17,  18,  19],
        [ 20,  21,  22],
        [ 23,  24,  25],
        [ 26,  27,  28],
        [ 29,  30,  31],
        [ 32,  33,  34],
        [ 35,  36,  37],
        [ 38,  39,  40],
        [ 41,  42,  43]],

       [[ 44,  45,  46],
        [ 47,  48,  49],
        [ 50,  51,  52],
        [ 53,  54,  55],
        [ 56,  57,  58],
        [ 59,  60,  61],
        [ 62,  63,  64],
        [ 65,  66,  67],
        [ 68,  69,  70],
        [ 71,  72,  73],
        [ 74,  75,  76],
        [ 77,  78,  79],
        [ 80,  81,  82],
        [ 83,  84,  85],
        [ 86,  87,  88]],

       [[ 89,  90,  91],
        [ 92,  93,  94],
        [ 95,  96,  97],
        [ 98, 499, 100],
        [101, 102, 103],
        [104, 105, 106],
        [107, 108, 109],
        [110, 111, 112],
        [113, 114, 115],
        [116, 117, 11

In [73]:
arr=np.arange(60)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [74]:
arr=arr.reshape(12,5)

In [75]:
arr1=np.arange(60)


In [76]:
arr1=arr1.reshape(12,5)

In [83]:
lst1=[1.0,2,3,4]
lst2=[3,4,5,6]
arr1=np.array(lst1)
arr2=np.array(lst2)
arr=arr1+arr2
arr

array([ 4.,  6.,  8., 10.])

In [ ]:
lst1=[1,2,3,4]# one list add to second list
lst2=[3,4,5,6]
lst1+lst2


[1, 2, 3, 4, 3, 4, 5, 6]

In [84]:
lst1=[1.0,2,3,4]
lst2=[3,4,5,6]
arr1=np.array(lst1)
arr2=np.array(lst2)
arr=arr1*arr2
arr

array([ 3.,  8., 15., 24.])

In [ ]:
arr=np.random.random(10)# 1d arr
arr

array([0.88179899, 0.11615079, 0.31975132, 0.20252385, 0.34762492,
       0.04635924, 0.14722172, 0.06089055, 0.29043337, 0.74488245])

In [ ]:
arr=np.random.randint(1,5,9).reshape(3,3)# 9 total element hai  rndom number b\w the 1,5 create 2d 1,5to b\w value
arr

array([[2, 3, 1],
       [4, 1, 1],
       [2, 1, 4]])

In [ ]:
arr=np.random.randint(1,5,(3,3,3))# 9 rndom number b\w the 1,5,3d array
arr

array([[[3, 2, 3],
        [2, 2, 3],
        [4, 4, 1]],

       [[4, 1, 2],
        [2, 4, 2],
        [3, 1, 2]],

       [[1, 3, 1],
        [1, 2, 2],
        [4, 1, 2]]])

In [63]:
arr=np.random.random(10)     # define only 10 element 
arr

array([0.78172669, 0.08903847, 0.15751772, 0.27398192, 0.51820887,
       0.41471135, 0.15464804, 0.35123658, 0.91009785, 0.50613849])

In [62]:
arr=np.random.random((5,2))     # define only 10 element 
arr

array([[0.3924901 , 0.42464841],
       [0.93141624, 0.54634823],
       [0.42227954, 0.19459426],
       [0.69144253, 0.7215225 ],
       [0.13150499, 0.24056278]])

In [ ]:
arr=np.arange(60).reshape(10,6)

print(arr)
print(arr.dtype)# check the data type u
print(arr.ndim)# check the dimansion 
print(arr.size)# check the elemment the array
print(arr.shape)# check the array shape 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]
int32
2
60
(10, 6)


In [70]:
arr.flatten()# 2d array to convert the 1d array with function of flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [71]:
arr.ravel()# 2d\3d array convert the 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
arr=np.random.randint(10)     # isme range hai automatlly generate 10 number ko only one value
arr

2

In [77]:
lst =[[1,2,3],[4,6,7]]
arr=np.array(lst)
arr


array([[1, 2, 3],
       [4, 6, 7]])

In [ ]:
arr.T.shape  # transport shape

(3, 2)

In [ ]:
arr.T # show value inverse transport shape

array([[1, 4],
       [2, 6],
       [3, 7]])

In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
lst=[1,2,3,4]

In [4]:
type(lst)

list

In [5]:
np.array(lst)

array([1, 2, 3, 4])

In [8]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
import numpy as np# crate list using arrange function
lst=list(range(0,20))
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [10]:
len(lst)

20

In [12]:
arr=np.arrange(0,20)


AttributeError: module 'numpy' has no attribute 'arrange'

In [43]:
arr.reshape(5,10,1)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])